name: Workflow on Merge into Main

on:
  push:
    branches:
      - main

concurrency:
  group: 'prd'

jobs:
  trigger-publish:
    name: Build and Publish Docker image
    uses: ./.github/workflows/reusable-publish.yml
    with:
      environment: prd
    secrets: inherit

  trigger-deploy:
    name: Deploy to Google Cloud Run
    needs: trigger-publish
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      environment: dev #change this to prd when ready
    secrets: inherit

  trigger-e2e:
    name: Execute e2e tests
    needs: trigger-deploy
    uses: ./.github/workflows/reusable-e2e.yml
    with:
        url: ${{ vars.PRD_URL }}
    secrets: inherit