name: Workflow on Pull Request

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: 'dev'
  cancel-in-progress: true

jobs:
  trigger-build:
    name: Lint, Test and Build
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit

  trigger-publish:
    name: Build and Publish Docker image
    needs: trigger-build
    uses: ./.github/workflows/reusable-publish.yml
    with:
        environment: stage
    secrets: inherit
 
  # since its not possible to dynamically register urls in zitadel e2e tests are executed against localhost
  trigger-e2e:
    name: Execute e2e tests
    needs: trigger-publish
    uses: ./.github/workflows/reusable-e2e.yml
    with:
      url: http://localhost:3000
    secrets: inherit