name: Workflow on Pull Request

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: 'dev'
  cancel-in-progress: true

jobs:
  trigger-build:
    name: Lint, Test and Build
    uses: ./.github/workflows/reusable-build.yml
    with:
      environment: stage
    secrets: inherit

  trigger-publish:
    name: Build and Publish Docker image
    needs: trigger-build
    uses: ./.github/workflows/reusable-publish.yml
    with:
        environment: stage
    secrets: inherit

# trigger-deployment:
  # Creating a PR automatically triggers a new vercel deployment, so this step is not necessary.
  # Ideally deploying would be triggered FROM github registry TO the test environment in this step.

  trigger-e2e:
    name: Execute e2e tests
    needs: trigger-publish
    uses: ./.github/workflows/reusable-e2e.yml
    with:
        url: ${{ vars.STAGE_URL }}
    secrets: inherit

