name: Workflow on Pull Request

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: 'dev'
  cancel-in-progress: true

jobs:
  trigger-build:
    name: Lint, Test and Build
    uses: ./.github/workflows/reusable-build.yml
    with:
      environment: stage
    secrets: inherit

  trigger-publish:
    name: Build and Publish Docker image
    needs: trigger-build
    uses: ./.github/workflows/reusable-publish.yml
    with:
        environment: stage
    secrets: inherit

  # Ideally this workflow would also deploy to a test environment

  # e2e test would be executed against the test environment => Not possible if the test environment's url is not registered in zitadel