name: Workflow on Pull Request

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: 'dev'
  cancel-in-progress: true

jobs:
  trigger-build:
    name: Lint, Test and Build
    uses: ./.github/workflows/reusable-build.yml
    with:
      environment: stage
    secrets: inherit

  trigger-publish:
    name: Build and Publish Docker image
    needs: trigger-build
    uses: ./.github/workflows/reusable-publish.yml
    with:
        environment: stage
    secrets: inherit

  # simulate the testing of the newly deployed version, but since the temporary vercel url cannot be configured in zitadel, this still tests the old version
  trigger-e2e:
    name: Execute e2e tests
    needs: trigger-publish
    uses: ./.github/workflows/reusable-e2e.yml
    with:
        url: ${{ vars.STAGE_URL }}
    secrets: inherit