name: Workflow on Push

on:
  push:
    branches:
      - feature/**
  workflow_dispatch:

concurrency:
  group: 'dev'

jobs:
  trigger-build:
    name: Lint, Test and Build
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit

  #TODO remove
  trigger-deploy:
    name: Deploy to Google Cloud Run
    uses: ./.github/workflows/reusable-deploy.yml
    secrets: inherit
