name: Workflow on Push

on:
  push:
    branches:
      - feature/**
  workflow_dispatch:

concurrency:
  group: 'dev'

jobs:
  trigger-build:
    name: Lint, Test and Build
    uses: ./.github/workflows/reusable-build.yml
    with:
        environment: dev
    secrets: inherit