name: Workflow on Push

on:
  push:
    branches:
      - feature/**
  workflow_dispatch:

concurrency:
  group: 'dev'

jobs:    # TODO: enable after deploy works
  #trigger-build:
   # name: Lint, Test and Build
   # uses: ./.github/workflows/reusable-build.yml
   # with:
   #     environment: dev
   # secrets: inherit
  
  # TODO: delete after this works
  trigger-deploy:
    name: Deploy to Google Cloud Run
    uses: ./.github/workflows/reusable-deploy.yml
    secrets: inherit