name: Push

on:
  push:
    branches:
      - feature/**
  workflow_dispatch:

concurrency:
  group: 'dev'
  cancel-in-progress: true

jobs:  
  trigger-ci:
    name: Lint, Test and Build
    uses: ./.github/workflows/reusable-build.yml
    with:
        environment: dev
    secrets: inherit