name: Reusable - Deploy

on:
  workflow_call:

permissions:
  packages: write
  id-token: write

jobs:
  deploy:
    name: Deploy with terraform
    runs-on: ubuntu-latest
    env:
      TF_CLI_ARGUMENTS: -var TAG=${{ github.sha }} -var apiUrl=${{ vars.NEXT_PUBLIC_QWACKER_API_URL }} -var nextauthUrl=${{ vars.PRD_URL }} -var nextauthSecret=${{ secrets.NEXTAUTH_SECRET }} -var issuer=${{ secrets.ZITADEL_ISSUER }} -var clientId=${{ secrets.ZITADEL_CLIENT_ID }}
    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout Project
        uses: actions/checkout@v3

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve ${{ env.TF_CLI_ARGUMENTS }}
