name: Reusable - Deploy

on:
  workflow_call:

permissions:
  packages: write
  id-token: write

jobs:
  deploy:
    name: Deploy with terraform
    env:
      TF_CLI_ARGUMENTS: -var apiUrl=${{ vars.NEXT_PUBLIC_QWACKER_API_URL }} -var nextauthUrl=${{ vars.PRD_URL }} -var nextauthSecret=${{ secrets.NEXTAUTH_SECRET }} -var issuer=${{ secrets.ZITADEL_ISSUER }} -var clientId=${{ secrets.ZITADEL_CLIENT_ID }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout Project
        uses: actions/checkout@v3

      - name: Login to Google Cloud Platform
        uses: docker/login-action@v2
        with:
          registry: europe-west6-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - id: 'gcloud'
        name: 'gcloud'
        run: gcloud auth application-default login

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

        #TODO: remove after apply is enabled
      - name: Terraform Plan
        id: plan
        run: terraform plan ${{ env.TF_CLI_ARGUMENTS }}

      #- name: Terraform Apply
      #  id: apply
      #  run: terraform apply -auto-approve ${{ env.TF_CLI_ARGUMENTS }}
