name: Reusable - Build and Publish docker image

on:
  workflow_call:
    inputs:
      environment:
        description: 'Controls the environment variables and the publish target'
        required: true
        default: 'stage'
        type: string

permissions:
  contents: read
  packages: write

jobs:
  publish:
    name: Build and publish docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: npm

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        if: ${{ inputs.environment == 'stage' }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.triggering_actor }}
          password: ${{ secrets.GITHUB_TOKEN   }}

      - name: Login to Google Container Registry
        if: ${{ inputs.environment == 'prd' }}
        uses: docker/login-action@v2
        with:
          registry: europe-west6-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Build and push to GitHub Container Registry
        if: ${{ inputs.environment == 'stage' }}
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            NODE_AUTH_TOKEN=${{ secrets.NODE_AUTH_TOKEN }}
            NEXT_PUBLIC_QWACKER_API_URL=${{vars.NEXT_PUBLIC_QWACKER_API_URL}}
            NEXTAUTH_URL=${{vars.STAGE_URL}}
            NEXTAUTH_SECRET=${{secrets.NEXTAUTH_SECRET}}
            ZITADEL_ISSUER=${{secrets.ZITADEL_ISSUER}}
            ZITADEL_CLIENT_ID=${{secrets.ZITADEL_CLIENT_ID}}
          push: true
          tags: |
            ghcr.io/smartive-education/z-index-next-app-at:latest
            ghcr.io/smartive-education/z-index-next-app-at:${{ github.sha }}
          cache-from: type=registry,ref=z-index-next-app-at:latest
          cache-to: type=inline

      - name: Build and push to Google Container Registry
        if: ${{ inputs.environment == 'prd' }}
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            NODE_AUTH_TOKEN=${{ secrets.NODE_AUTH_TOKEN }}
            NEXT_PUBLIC_QWACKER_API_URL=${{vars.NEXT_PUBLIC_QWACKER_API_URL}}
            NEXTAUTH_URL=${{vars.PRD_URL}}
            NEXTAUTH_SECRET=${{secrets.NEXTAUTH_SECRET}}
            ZITADEL_ISSUER=${{secrets.ZITADEL_ISSUER}}
            ZITADEL_CLIENT_ID=${{secrets.ZITADEL_CLIENT_ID}}
          push: true
          tags: |
            europe-west6-docker.pkg.dev/hip-polymer-387617/z-index-gcp-registry/z-index-next-app-at:latest
            europe-west6-docker.pkg.dev/hip-polymer-387617/z-index-gcp-registry/z-index-next-app-at:${{ github.sha }}
          cache-from: type=registry,ref=z-index-next-app-at:latest
          cache-to: type=inline
